version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    container_name: wedding-database-postgres
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass1wrd
      - POSTGRES_DB=wedding_dev
    ports:
      - 5432:5432
    hostname: "postgres2"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
